version: '3.9'

services:
  ros-px4-humble-2:
      image: ros-px4-humble:latest
      container_name: ros-px4-humble-2
      mem_limit: "4g"        # Set memory limit to 4GB
      cpu_shares: 1024   
      build:
        context: .
        dockerfile: ./humble-px4.Dockerfile
      volumes:
        - /etc/group:/etc/group:ro
        - /etc/passwd:/etc/passwd:ro
        - /etc/shadow:/etc/shadow:ro
        - /etc/sudoers.d:/etc/sudoers.d:ro
        - /home:/home:rw
        - ./ws:/edra/ws:ro
      environment:
        - DISPLAY=:0
        - LIBGL_ALWAYS_SOFTWARE=1
      network_mode: "host"
      stdin_open: true
      tty: true

